version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.9.0

executors:
  cli:
    docker:
      - image: circleci/circleci-cli

jobs:
  production-publish:
    executor: cli
    steps:
      - checkout
      - run: circleci orb publish promote tiendanube/eks@dev:${CIRCLE_BRANCH} patch --token $CIRCLE_TOKEN

workflows:
  btd:
    jobs:
      - orb-tools/lint:
          name: lint
      - orb-tools/pack:
          name: pack
          requires:
            - lint
      - orb-tools/publish-dev:
          name: publish-dev
          orb-name: tiendanube/eks
          context: orbs
      - promote-production:
          type: approval
          requires:
            - publish-dev
          filters:
            branches:
              only:
                - master
      - production-publish:
          context: orbs
          requires:
            - promote-production
          filters:
            branches:
              only:
                - master
