version: 2.1

orbs:
  orb-tools: circleci/orb-tools@3.0.0

workflows:
  btd:
    jobs:
      - orb-tools/publish:
          orb-path: src/orb.yml
          orb-ref: tiendanube/eks@dev:${CIRCLE_BRANCH}
          validate: true
