version: 2.1

description: Install tools to interact with AWS EKS

examples:
  deploy:
    description: Deploy to EKS
    usage:
      version: 2.1
      orbs:
        eks: tiendanube/eks@1.0.0
      workflows:
        deploy:
          jobs:
            - eks/deploy:
                cluster_name: cluster_name
                region: region
                steps:
                  - run:
                      command: |
                        kubectl apply -f bundle.yml
                        kubectl apply -f deployment.yml

executors:
  default:
    docker:
      - image: tiendanube/circleci-eks:v1.0.0

commands:
  authenticate_eks_cluster:
    description: Authenticate to EKS Cluster
    parameters:
      cluster_name:
        type: string
        description: EKS cluster name
      region:
        type: string
        description: AWS region where the eks cluster is located
    steps:
      - run:
          name: Set default AWS Region
          command: |
            aws configure set region << parameters.region >>
      - run:
          name: Authenticate to EKS Cluster
          command: aws eks update-kubeconfig --name << parameters.cluster_name >> --region << parameters.region >>

jobs:
  deploy:
    description: Authenticate to eks cluster and run the steps provided
    executor: default
    parameters:
      cluster_name:
        type: string
        description: EKS cluster name
      region:
        type: string
        description: AWS region where the eks cluster is located
      steps:
        type: steps
        description: Steps to deploy your application (e.g. kubectl apply -f deployment.yml)
    steps:
      - checkout
      - authenticate_eks_cluster:
          cluster_name: << parameters.cluster_name >>
          region: << parameters.region >>
      - steps: << parameters.steps >>

  helm-deploy:
    description: Deploy the given Helm chart to EKS Cluster
    executor: default
    parameters:
      cluster_name:
        type: string
        description: EKS cluster name
      region:
        type: string
        description: AWS region where the eks cluster is located
      s3-chart-repo:
        type: string
        description: Additional helm chart repository
        default:
      release-name:
        type: string
        description: Helm release name
      values-file:
        type: string
        description: Helm values file
      namespace:
        type: string
        description: Namespace where the chart will be installed
      chart:
        type: string
        description: Chart that will be installed
      image-tag:
        type: string
        description: Which image tag will be installed
        default: ${CIRCLE_SHA1:0:7}
      checkout:
        type: boolean
        description: Boolean for whether or not to checkout as a first step. Default is true.
        default: true
    steps:
      - when:
          condition: << parameters.checkout >>
          steps:
            - checkout
      - authenticate_eks_cluster:
          cluster_name: << parameters.cluster_name >>
          region: << parameters.region >>
      - when:
          condition: << parameters.s3-chart-repo >>
          name: Add additional helm repo
          steps:
            - run: helm repo add << parameters.s3-chart-repo >> s3://<< parameters.s3-chart-repo >>/
      - run:
          name: Upgrade helm chart
          command: >
            helm upgrade
            --install << parameters.release-name >>
            --values << parameters.values-file >>
            --set-string image.tag="<< parameters.image-tag >>"
            --namespace << parameters.namespace >>
            << parameters.chart >>
      - run:
          name: Check the release status
          command: |
            sleep 10
            helm status << parameters.release-name >>
