version: 2.1

description: Install tools to interact with AWS EKS

examples:
  install_kubectl:
    description: Install kubectl
    usage:
      version: 2.1

      orbs:
        eks: tiendanube/eks@1.0.0

      jobs:
        build:
          docker:
            - image: circleci/openjdk:8-jdk
          steps:
            - checkout
            - eks/install_kubectl

  install_aws_iam_authenticator:
    description: Install AWS IAM Authenticator
    usage:
      version: 2.1
      orbs:
        eks: tiendanube/eks@1.0.0
      jobs:
        build:
          docker:
            - image: circleci/openjdk:8-jdk
          steps:
            - checkout
            - eks/install_aws_iam_authenticator

  deploy:
    description: Deploy to EKS
    usage:
      version: 2.1
      orbs:
        eks: tiendanube/eks@1.0.0
      workflows:
        deploy:
          jobs:
            - eks/deploy:
                cluster_name: cluster_name
                region: region
                steps:
                  - run:
                      command: |
                        kubectl apply -f bundle.yml
                        kubectl apply -f deployment.yml

orbs:
  aws-cli: circleci/aws-cli@0.1.4

executors:
  eks:
    docker:
      - image: circleci/openjdk:8-jdk-node

commands:
  install_kubectl:
    description: Install kubectl
    steps:
      - run:
          command: |
            curl -o kubectl https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin

  install_aws_iam_authenticator:
    description: Install AWS IAM Authenticator
    steps:
      - run:
          command: |
            curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-07-26/bin/linux/amd64/aws-iam-authenticator
            chmod +x ./aws-iam-authenticator
            sudo mv ./aws-iam-authenticator /usr/local/bin

  authenticate_eks_cluster:
    description: Authenticate to EKS Cluster
    parameters:
      cluster_name:
        type: string
        description: EKS cluster name
      region:
        type: string
        description: AWS region where the eks cluster is located
    steps:
      - run:
          command: aws eks update-kubeconfig --name << parameters.cluster_name >> --region << parameters.region >>

jobs:
  deploy:
    description: |
      Checkout, install awscli, kubectl, aws iam authenticator, authenticate to eks cluster and run the steps provided
    executor: eks
    parameters:
      cluster_name:
        type: string
        description: EKS cluster name
      region:
        type: string
        description: AWS region where the eks cluster is located
      steps:
        type: steps
        description: Steps to deploy your application (e.g. kubectl apply -f deployment.yml)
    steps:
      - checkout
      - aws-cli/install
      - install_kubectl
      - install_aws_iam_authenticator
      - authenticate_eks_cluster:
          cluster_name: << parameters.cluster_name >>
          region: << parameters.region >>
      - steps: << parameters.steps >>
